
name: Terraform CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      # Dev environment
      - name: Terraform Init (Dev)
        working-directory: ./envs/dev
        run: terraform init

      - name: Terraform Validate (Dev)
        working-directory: ./envs/dev
        run: terraform validate

      - name: Terraform Format Check (Dev)
        working-directory: ./envs/dev
        run: terraform fmt -check

        # Plan (Dev) - detects breaking changes
      - name: Terraform Plan (Dev)
        working-directory: ./envs/dev
        run: terraform plan -out=tfplan

      # Prod environment
      - name: Terraform Init (Prod)
        working-directory: ./envs/prod
        run: terraform init

      - name: Terraform Validate (Prod)
        working-directory: ./envs/prod
        run: terraform validate

      - name: Terraform Format Check (Prod)
        working-directory: ./envs/prod
        run: terraform fmt -check
